### PR TITLE
change struct ViewManager to an interface

### PR DESCRIPTION
**Pull request by geange**

### CODE REVIEW

**Review by chenjiandongx — COMMENTED** [review]
What's your point to change the ViewManager struct to an interface?

**Comment by geange** [comment]
Hide the actual implementation, users don't need to know the actual struct. Users should not be able to modify the structure directly, only use functions to modify data.

**Comment by chenjiandongx** [comment]
In fact, there is only the `Views` var is visible which makes it possible to customize the Chart style as we said in the Readme

> Viewer wraps a go-echarts *charts.Line instance that means all options/features on it could be used.

**Comment by geange** [comment]
If the viewer is a pointer object, you still can customize the Chart style?

**Comment by chenjiandongx** [comment]
obviously, it can

```golang
	mgr := statsview.New()
	for _, view := range mgr.Views {
		if view.Name() == viewer.VGoroutine {
			view.View().SetGlobalOptions(charts.WithTitleOpts(opts.Title{
				Title: "My customize title",
			}))
		}
	}
	go mgr.Start()
```

image

**Comment by geange** [comment]
But I think this code should be more clearly? And maybe change `statsview.New()` => `statsview.Default()` ?

* `statsview.New()`: register zero view
* `statsview.Default()`: register the default views

```golang
view := viewer.NewGoroutinesViewer()
view.View().SetGlobalOptions(charts.WithTitleOpts(opts.Title{
    Title: "My customize title",
}))

mgr := statsview.New()
mgr.Register(view)
go mgr.Start()

```

**Comment by chenjiandongx** [comment]
statsview is designed as the `single-instance`, so....

**Pull request closed without merging**
